# Generated by Django 2.0.1 on 2018-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.AddField(
            model_name='company',
            name='content',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
